project:
  type: website
  output-dir: docs
  resources:
    - "sequential_vs_parallel.gif"

website:
  title: "Xavier Gonzalez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks.qmd
        text: Talks
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true